use_frameworks!

platform :ios, '8.0'

target 'LTCoreKit_Example' do
  pod 'LTCoreKit', :path => '../'

  target 'LTCoreKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
